#!/bin/bash

set -eu

VCGEN="$(command -v vcgencmd)"
PREFIX="rpi_"

# get temperatures
{
  echo "# HELP ${PREFIX}temperature_celsius Temperatures of the components.";
  echo "# TYPE ${PREFIX}temperature_celsius gauge";
}
for SENSOR in $(ls /sys/class/thermal/); do
  unset CPU_TEMP_CELSIUS
  unset CPU_TYPE

  CPU_TEMP_CELSIUS="$(awk '{printf "%.3f", $1/1000}' /sys/class/thermal/${SENSOR}/temp)" || true
  CPU_TEMP_CELSIUS="${CPU_TEMP_CELSIUS:=0}"
  CPU_TYPE="$(cat /sys/class/thermal/${SENSOR}/type)"
  CPU_TYPE="${CPU_TYPE:=N/A}"

  echo "${PREFIX}temperature_celsius{sensor=\"${SENSOR}\",type=\"${CPU_TYPE}\"} ${CPU_TEMP_CELSIUS}"
done

# get component frequencies
{
  echo "# HELP ${PREFIX}frequency_hz Clock frequencies of the components.";
  echo "# TYPE ${PREFIX}frequency_hz gauge";
}
declare -a FREQ_COMPONENTS=("arm" "core" "h264" "isp" "v3d" "uart" "pwm" "emmc" "pixel" "hdmi")
for FREQ_COMPONENT in "${FREQ_COMPONENTS[@]}"; do
  unset FREQUENCE

  FREQUENCE="$($VCGEN measure_clock "${FREQ_COMPONENT}" | cut -d '=' -f 2)" || true
  FREQUENCE="${FREQUENCE:=0}"

  echo "${PREFIX}frequency_hz{component=\"${FREQ_COMPONENT}\"} ${FREQUENCE}"
done

# get component voltages
{
  echo "# HELP ${PREFIX}voltage_volts Voltages of the components.";
  echo "# TYPE ${PREFIX}voltage_volts gauge";
}
declare -a VOLT_COMPONENTS=("core" "sdram_c" "sdram_i" "sdram_p")
for VOLT_COMPONENT in "${VOLT_COMPONENTS[@]}"; do
  unset VOLTS

  VOLTS="$($VCGEN measure_volts "${VOLT_COMPONENT}" | cut -d '=' -f 2 | sed 's/V$//')" || true
  VOLTS="${VOLTS:=0}"

  echo "${PREFIX}voltage_volts{component=\"${VOLT_COMPONENT}\"} ${VOLTS}"
done

# get memory split of CPU vs GPU
{
  echo "# HELP ${PREFIX}memory_bytes Memory split of CPU and GPU.";
  echo "# TYPE ${PREFIX}memory_bytes gauge";
}
declare -a MEM_COMPONENTS=("arm" "gpu")
for MEM_COMPONENT in "${MEM_COMPONENTS[@]}"; do
  unset MEM

  MEM="$($VCGEN get_mem "${MEM_COMPONENT}" | cut -d '=' -f 2 | sed 's/M$//')" || true
  MEM="${MEM:=0}"
  MEM="$(( MEM * 1024 * 1024 ))"

  echo "${PREFIX}memory_bytes{component=\"${MEM_COMPONENT}\"} ${MEM}"
done

